---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull shwetanknaveen/spe_mini_project

    - name: running container
      shell: docker run -it -d shwetanknaveen/spe_mini_project /bin/bash
